name: SPINacc CI

on:
  push:
    branches:
      - "**"
    pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.12'
      - name: Install linting tools
        run: pip install ruff==0.9.1
      - name: ruff python interface checks
        run: |
          ruff format --check tests Tools

  build:
    runs-on: ubuntu-latest
    needs: lint
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Get ZENODO data, packdata and DEF_Trunk config
        run: |
          git clone https://github.com/ma595/SPINacc-data.git
          bash setup-data.sh ./SPINacc-data/run/DEF_Trunk/
      - name: Run first test
        run: |
          DEF_DIR=$(readlink -f SPINacc-data/run/DEF_Trunk/)
          # stomate files in varlist.json
          python3 main.py $DEF_DIR

          # VLAD_DATA="$(readlink -f ./SPINacc-data)/vlad_files/vlad_files/"
          # sed -i "s@/home/surface5/vbastri/SPINacc_ref@$VLAD_DATA@g" $varlist_json
          # pytest -v --capture=sys ./tests/test_task1.py

      # - name: Run first test
      #   run: |
      #     mkdir EXE_DIR
      #     mv SPINacc-data/reference/packdata.npy EXE_DIR/
      #     # change the reference directory in MLacc.def
      #     ls
      #     reference=$(readlink -f ./SPINacc-data/reference/)
      #     echo $reference
      #     sed -i "s@/home/surface10/mrasolon/files_for_zenodo/reference/EXE_DIR/@${reference}/\n/@g" ./DEF_Trunk/MLacc.def

      #     # change execution directory in MLacc.def
      #     EXE_DIR=$(readlink -f ./EXE_DIR)
      #     sed -i "s@/home/surface10/mrasolon/SPINacc_24_01_05/EXE_DIR/@$EXE_DIR/@g" ./DEF_Trunk/MLacc.def

      #     # stomate files in varlist.json
      #     varlist_json="$(readlink -f DEF_Trunk)/varlist.json"
      #     VLAD_DATA="$(readlink -f ./SPINacc-data)/vlad_files/vlad_files/"
      #     sed -i "s@/home/surface5/vbastri/SPINacc_ref@$VLAD_DATA@g" $varlist_json
