name: SPINacc CI

on:
  push:
    branches:
      - "**"
    pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.12'
      - name: Install linting tools
        run: pip install ruff==0.9.1
      - name: ruff python interface checks
        run: |
          ruff format --check tests Tools

  build:
    runs-on: ubuntu-latest
    needs: lint
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Get sample of reference data
        run: |
          git clone https://github.com/ma595/SPINacc-data.git
      - name: Run first test
        run: |
          mkdir EXE_DIR
          mv SPINacc-data/reference/auxil.npy EXE_DIR/
          mv SPINacc-data/reference/packdata.npy EXE_DIR/
          sed -i '/# config\[3\] : task/{n;s/.*/1/}' ./DEF_Trunk/MLacc.def
          # read previous results
          sed -i '/# config\[7\] : task/{n;s/.*/1/}' ./DEF_Trunk/MLacc.def
          # change the reference directory in MLacc.def
          reference=$(readlink -f ./reference)
          sed -i "s@/home/surface10/mrasolon/files_for_zenodo/reference/EXE_DIR/@$reference/@g" ./DEF_Trunk/MLacc.def
          cat ./DEF_Trunk/MLacc.def
          python main.py DEF_Trunk/
          pytest -v --capture=sys ./tests/test_task1.py
