name: SPINacc formatting checks

on:
  push:
    branches:
      - "**"
    pull_request:
      branches:
        - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.21'
      - name: Install linting tools
        run: pip install ruff==0.9.1
      - name: ruff python interface checks
        run: |
          ruff format --check tests Tools
